### ISSUE TITLE
image detail page shown empty without any error

### ISSUE THREAD

**Issue by typoworx-de** [jc21/docker-registry-ui#29]
I've just deployed docker-registry-ui. I really like the simple way to deploy it and the lightweight UI. But at least for me, it's shown "very lightful" after clicking on an image-name. The front-page works fine showing my images very quick. The detail page only shows the pure layout but no body, content or error. Also browser console and network-debug tab shows no culprit.

The registry backend ist docker registry:2. Any idea what's wrong?

```yaml
version: "3.7"

networks:
  default:
    external: true

volumes:
  cert-storage:
    name: php-stack-cert-storage
    driver: local
    driver_opts:
      type: none
      device: "$HOME/.local/share/mkcert"
      o: bind
  docker-registry-storage:
  docker-registry-config:

services:
  docker-registry:
    image: registry:2
    restart: on-failure
    hostname: registry-api.php-stack.docker
    ports:
      - "127.0.0.11:5000:5000/tcp"
    networks:
      - default
    environment:
      #REGISTRY_HTTP_ADDR: "0.0.0.0:5000"
      REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/_wildcard.php-stack.docker.pem"
      REGISTRY_HTTP_TLS_KEY: "/certs/_wildcard.php-stack.docker-key.pem"
      REGISTRY_STORAGE_DELETE_ENABLED: true
    volumes:
      - "cert-storage:/certs"
      - "docker-registry-storage:/var/lib/registry"
      - "docker-registry-config:/etc/docker/registry"

  docker-registry-ui:
    image: jc21/registry-ui
    restart: on-failure
    depends_on:
      - docker-registry
    hostname: registry.php-stack.docker
    networks:
      - default
    environment:
      SUPPRESS_NO_CONFIG_WARNING: true
      REGISTRY_HOST: registry-api.php-stack.docker:5000
      REGISTRY_DOMAIN: registry-api.php-stack.docker:5000
      REGISTRY_SSL: true
      REGISTRY_STORAGE_DELETE_ENABLED: true
      #REGISTRY_USER:
      #REGISTRY_PASS:
```
